#!/usr/bin/env python3
# This is not a general-purpose script. It is a minimal, one-off hack
# to solve the bootstrapping problem of extracting the rst2zsh script
# from its own literate source. It has minimal error handling.

import fileinput

from docutils.core import publish_doctree
from docutils.nodes import NodeVisitor


class ZshCodeExtractor(NodeVisitor):
    def visit_literal_block(self, node):
        if node.rawsource.startswith(".. spelling:"):
            return
        print(node.astext())

    def unknown_visit(self, node):
        pass


content = "".join(line for line in fileinput.input())

doctree = publish_doctree(content, settings_overrides={"report_level": 4})
extractor = ZshCodeExtractor(doctree)
doctree.walk(extractor)
