name: Generate and deploy HTML

on:
  push:
    paths:
      - .github/workflows/build_HTML.yml
      - .images/**
      - conf.py
      - requirements.txt
      - "**.rst"

permissions:
  contents: read

jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          python-version: ${{ matrix.python-version }}
          version: 0.9.2
          activate-environment: true
          cache-dependency-glob: requirements.txt

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Build HTML with Sphinx
        run: |
          uv run sphinx-build -M html . _build
          # upload-pages-artifact@v4 doesn't include files beginning with a dot
          mv _build/html/{.,_}buildinfo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: _build/html

  deploy:
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write

    needs: build
    if: github.ref == 'refs/heads/main'
    # The deployment environment must be configured in repository settings
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
