on:
  push:
    branches:
      - main

name: Generate and deploy HTML

permissions: write-all

jobs:
  default_build:
    name: build
    runs-on: ubuntu-24.04

    steps:
      - name: Install Debian dependencies
        run: |
          sudo apt install python3-docutils python3-pygments

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: gh-pages

      - name: Build
        run: |
          git show origin/main:README.rst |
            sed 's,^\([^\.].*:\):$$,\1\n\n.. code:: zsh,' |
            rst2html \
              --link-stylesheet \
              --rfc-references \
              --smart-quotes=yes \
              --source-url=https://github.com/JNRowe/river-configs \
              --strict \
              --stylesheet css/rhythm.css,css/monokai.css \
              --syntax-highlight=short \
              /dev/stdin index.html

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          git commit \
            --message "Regenerated on $(git rev-parse --short $GITHUB_SHA)" \
            || exit 0
          git push
