on:
  pull_request:
  push:
    branches:
      - main

name: Generate and deploy HTML

jobs:
  default_build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Install Debian dependencies
        run: |
          sudo apt install python3-sphinx python3-sphinx-rtd-theme python3-sphinxcontrib.spelling

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: _build/html

      # This shouldn't be necessary, but actions/checkout doesn't have
      # --no-checkout support.  If we don't manually scrub the tree obsolete
      # files won't be dropped
      - name: Scrub gh-pages tree
        if: github.ref == 'refs/heads/main'
        working-directory: _build/html
        run: |
          git ls-files | grep -v .nojekyll | xargs rm

      - name: Build
        run: |
          touch _build/html/.nojekyll
          sphinx-build -M html . _build

      - name: Commit and push if it changed
        if: github.ref == 'refs/heads/main'
        working-directory: _build/html
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          git commit \
            --message "Regenerated on $(git rev-parse --short $GITHUB_SHA)" \
            || exit 0
          git push
