on:
  pull_request:
  push:
    branches:
      - main

name: Generate and deploy HTML

jobs:
  default_build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Install Debian dependencies
        run: |
          sudo apt install python3-sphinx python3-sphinx-rtd-theme

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: gh-pages
          path: _build/html

      - name: Build
        run: |
          sphinx-build -M html . _build

      - name: Commit and push if it changed
        if: github.ref == 'refs/heads/main'
        run: |
          cd _build/html
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          git commit \
            --message "Regenerated on $(git rev-parse --short $GITHUB_SHA)" \
            || exit 0
          git push
