name: Generate and deploy HTML

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build HTML with Sphinx
        run: |
          sphinx-build -M html . _build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    name: Deploy to GitHub Pages
    permissions:
      pages: write
      id-token: write

    needs: build
    if: github.ref == 'refs/heads/main'
    # The deployment environment must be configured in repository settings
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
